name: cupertino_typography_example
description: "Demonstrates how to use the cupertino_typography package."
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_typography:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
